title: "Lucas de Oliveira Leal"
description: "Exercicios de processamento digital de imagens"
author: ""
url: "https://username.github.io" 
theme: minima

header_pages:
  - index.md
  - about.md
  - test.md

