title: "Lucas Leal"
description: "Exercicios de processamento digital de imagens"
author:
  name: "Lucas de Oliveira Leal"
  email: "lucolileal@gmail.com"
  url: "https://username.github.io"
url: "https://username.github.io" 
theme: minima
skin: dark 
paginate: 5
