title: "Exercicios de Processamento digital de imagens"
description: "Exercicios de processamento digital de imagens"
author: "Lucas de Oliveira Leal"
url: "https://username.github.io" 
theme: minima
minima:
  skin: dark
  
paginate: 5
